'use client';
import { useEffect, useMemo, useState } from 'react';
import { Flame, Minus, Package, Plus, ShoppingBag, Truck } from 'lucide-react';
import AppDock from './components/AppDock';

type Category='pipes'|'flavours'|'extras'|'delivery';
const flavours=[['lady','Lady Killer'],['gum','Gum & Mint'],['cream','Cream Mint'],['apple','Double Apple']] as const;
const money=(n:number)=>`R${n.toLocaleString('en-ZA')}`;

export default function Store(){
  const [category,setCategory]=useState<Category>('pipes');
  const [cart,setCart]=useState<Record<string,number>>({pipe:2,lady:2,gum:1,cream:1,coal:2,stove:1});
  const [delivery,setDelivery]=useState(true);
  const [activeBooking,setActiveBooking]=useState<string|null>(null);
  useEffect(()=>{const raw=localStorage.getItem('chill-pipe-booking');if(raw)setActiveBooking(JSON.parse(raw).reference||null)},[]);
  const adjust=(id:string,change:number)=>setCart(current=>({...current,[id]:Math.max(0,Math.min(10,(current[id]||0)+change))}));
  const total=useMemo(()=>550*(cart.pipe||0)+50*((cart.coal||0)+flavours.reduce((sum,[id])=>sum+(cart[id]||0),0))+150*(cart.stove||0),[cart]);
  const count=Object.values(cart).reduce((sum,n)=>sum+n,0);
  function checkout(){const selectedFlavours=flavours.flatMap(([id,name])=>Array.from({length:cart[id]||0},()=>name));localStorage.setItem('chill-pipe-order',JSON.stringify({quantities:{pipe:cart.pipe||0,coal:cart.coal||0,stove:cart.stove||0},selectedFlavours,delivery,customer:{name:'',phone:'',date:'',location:'',notes:''},total}));window.location.href='/checkout';}
  const Stepper=({id}:{id:string})=>{const qty=cart[id]||0;return <div className="session-stepper"><button aria-label={`Remove one ${id}`} onClick={()=>adjust(id,-1)} disabled={!qty}><Minus/></button><span>{qty}</span><button aria-label={`Add one ${id}`} onClick={()=>adjust(id,1)}><Plus/></button></div>};
  return <main className="session-app"><header className="session-header"><a href="/"><img src="/chill-pipe-logo.png" alt="The Chill Pipe"/></a><div><span>24-hour rentals</span><strong>Build your session</strong></div></header><section className="session-welcome"><div className="welcome-mark"><img src="/chill-pipe-logo.png" alt=""/></div><div><p>Good evening</p><h1>What are we lighting up tonight?</h1><span>Choose your setup, send the request and track everything through to your deposit refund.</span></div>{activeBooking&&<a href="/track">Track {activeBooking}</a>}</section><section className="session-menu"><div className="menu-heading"><div><p>Your order</p><h2>Build your setup</h2></div><span>{count} items</span></div><nav className="session-tabs">{([['pipes','Pipes'],['flavours','Flavours'],['extras','Coal & extras'],['delivery','Delivery']] as const).map(([id,label])=><button key={id} className={category===id?'active':''} onClick={()=>setCategory(id)}>{id==='pipes'?<img src="/chill-pipe-logo.png" alt=""/>:id==='flavours'?<Flame/>:id==='extras'?<Package/>:<Truck/>}<span>{label}</span></button>)}</nav><div className="session-panel">{category==='pipes'&&<article className="session-product featured"><div className="session-icon"><img src="/chill-pipe-logo.png" alt=""/></div><div><small>24-hour rental</small><h3>Classic hookah pipe</h3><p>Cleaned, complete and ready for your session.</p><strong>R550</strong></div><Stepper id="pipe"/></article>}{category==='flavours'&&<div className="session-flavours">{flavours.map(([id,name])=><article className={(cart[id]||0)>0?'selected':''} key={id}><div><Flame/><small>R50 each</small></div><h3>{name}</h3><Stepper id={id}/></article>)}</div>}{category==='extras'&&<div className="session-stack"><article className="session-product"><div className="session-icon dark"><Flame/></div><div><small>36 pieces</small><h3>Coal box</h3><p>One box per hookah recommended.</p><strong>R50</strong></div><Stepper id="coal"/></article><article className="session-product"><div className="session-icon"><Package/></div><div><small>Optional extra</small><h3>Coal stove</h3><p>Lights your coals quickly and evenly.</p><strong>R150</strong></div><Stepper id="stove"/></article></div>}{category==='delivery'&&<button className={delivery?'delivery-choice selected':'delivery-choice'} onClick={()=>setDelivery(value=>!value)}><Truck/><span><strong>Delivery & collection</strong><small>Priced manually after we confirm your location.</small></span><i>{delivery?'Selected':'Add'}</i></button>}</div></section><div className="session-summary"><div><small>Estimated total</small><strong>{money(total)}</strong><span>{delivery?' + delivery / collection':' · customer collection'}</span></div><button onClick={checkout} disabled={!count}><ShoppingBag/>Review order</button></div><AppDock active="home"/></main>;
}
