'use client';
import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Clock3, Home, MapPin, Menu, Minus, PackageCheck, Plus, Search, ShoppingBag, Store, Truck, UserRound } from 'lucide-react';

type Step='home'|'flavours'|'delivery';
type Flavour={id:string;name:string;description:string;image:string};
const flavours:Flavour[]=[
  {id:'lady',name:'Lady Killer',description:'Sweet berries, citrus and a smooth finish.',image:'/lady-killer.webp'},
  {id:'gum',name:'Gum & Mint',description:'Cool, fresh and always a favourite.',image:'/gum-mint.webp'},
  {id:'cream',name:'Cream Mint',description:'Silky, mellow and finished with a cool mint lift.',image:'/cream-mint.webp'},
  {id:'blueberry',name:'Blueberry Mint',description:'Juicy blueberry with a crisp, refreshing finish.',image:'/blueberry-mint.webp'},
  {id:'watermelon',name:'Watermelon Chill',description:'Bright watermelon sweetness served ice-cool.',image:'/watermelon-chill.webp'},
  {id:'apple',name:'Double Apple',description:'A rich red-and-green apple hookah classic.',image:'/double-apple.webp'},
];
const money=(n:number)=>`R${n.toLocaleString('en-ZA')}`;

function BrandLogo(){return <a className="flow-brand" href="/" aria-label="The Chill Pipe home"><img src="/chill-pipe-logo.webp" alt="The Chill Pipe"/><span>Hookah rentals</span></a>}
function Header({step,cart,onBack}:{step:Step;cart:number;onBack?:()=>void}){return <header className="flow-header">{onBack?<button aria-label="Go back" onClick={onBack}><ArrowLeft/></button>:<BrandLogo/>}{onBack&&<BrandLogo/>}<div className="flow-head-actions"><button aria-label="View order"><ShoppingBag/><i>{cart}</i></button><button aria-label="Open menu"><Menu/></button></div></header>}
function PrimaryButton({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <button className="flow-primary" onClick={onClick}>{children}<ArrowRight/></button>}
function BottomNav({active}:{active:string}){return <nav className="flow-nav"><a className={active==='home'?'active':''} href="/"><Home/><span>Home</span></a><button className={active==='flavours'?'active':''}><span className="leaf">◒</span><span>Flavours</span></button><a href="/delivery"><Truck/><span>Delivery</span></a><a href="/how-it-works"><UserRound/><span>Profile</span></a></nav>}
function Quantity({value,onChange}:{value:number;onChange:(value:number)=>void}){return <div className="flow-quantity"><button aria-label="Decrease quantity" disabled={value===1} onClick={()=>onChange(Math.max(1,value-1))}><Minus/></button><span>{value}</span><button aria-label="Increase quantity" onClick={()=>onChange(Math.min(10,value+1))}><Plus/></button></div>}
function FlavourCard({flavour,selected,onToggle}:{flavour:Flavour;selected:boolean;onToggle:()=>void}){return <article className={selected?'flow-flavour selected':'flow-flavour'}><img src={flavour.image} alt="" loading="lazy" decoding="async"/><div><h3>{flavour.name}</h3><p>{flavour.description}</p></div><button aria-label={selected?`Remove ${flavour.name}`:`Add ${flavour.name}`} onClick={onToggle}>{selected?<Check/>:<Plus/>}</button></article>}
function DeliveryOption({selected,icon:Icon,title,copy,onClick}:{selected:boolean;icon:typeof Truck;title:string;copy:string;onClick:()=>void}){return <button className={selected?'delivery-option-card selected':'delivery-option-card'} onClick={onClick}><span><Icon/></span><div><strong>{title}</strong><small>{copy}</small></div><i>{selected?<Check/>:null}</i></button>}

export default function BookingFlow(){const [step,setStep]=useState<Step>('home');const [pipeQty,setPipeQty]=useState(1);const [selected,setSelected]=useState<string[]>(['lady','gum']);const [flavourSearch,setFlavourSearch]=useState('');const [delivery,setDelivery]=useState(true);const [address,setAddress]=useState('');const [date,setDate]=useState('');const flavourLimit=pipeQty*2;const visibleFlavours=flavours.filter(item=>`${item.name} ${item.description}`.toLowerCase().includes(flavourSearch.trim().toLowerCase()));const total=useMemo(()=>pipeQty*550+selected.length*50,[pipeQty,selected]);const cart=pipeQty+selected.length;function toggleFlavour(id:string){setSelected(current=>current.includes(id)?current.filter(item=>item!==id):current.length<flavourLimit?[...current,id]:current)}function finish(){localStorage.setItem('chill-pipe-order',JSON.stringify({quantities:{pipe:pipeQty,coal:0,stove:0},selectedFlavours:flavours.filter(item=>selected.includes(item.id)).map(item=>item.name),delivery,customer:{name:'',phone:'',date,location:address,notes:''},total}));window.location.href='/checkout'}
  if(step==='home')return <main className="flow-app dark"><Header step={step} cart={cart}/><section className="flow-home-hero"><img src="/hookah-hero.webp" alt="Premium glass hookah in a dark lounge"/><p>Good<br/>people<br/>better<br/>sessions</p><div><h1>Build your<br/>session</h1><span>Premium hookahs. Unforgettable vibes.<br/>Delivered to you.</span></div></section><section className="product-sheet"><div className="sheet-title"><span>Choose your setup</span><strong>{money(total)}</strong></div><div className="product-carousel"><article className="flow-product selected"><div className="product-photo"><img src="/hookah-hero.webp" alt="Classic hookah"/></div><h2>Classic hookah · R550</h2><p>Everything you need for a smooth session.</p><Quantity value={pipeQty} onChange={setPipeQty}/></article><article className="flow-product muted-card"><div className="product-photo"><img src="/hookah-hero.webp" alt="Premium hookah"/></div><h2>Premium hookah</h2><p>A signature setup. Coming soon.</p><button aria-label="Premium hookah coming soon"><ArrowRight/></button></article></div><div className="carousel-dots"><i className="active"/><i/><i/></div><PrimaryButton onClick={()=>setStep('flavours')}>Choose flavours</PrimaryButton></section><BottomNav active="home"/></main>;
  if(step==='flavours')return <main className="flow-app"><section className="flow-photo-head"><img src="/hookah-hero.webp" alt="Hookah with drifting smoke"/><Header step={step} cart={cart} onBack={()=>setStep('home')}/><p>Same<br/>flavours<br/>bigger<br/>vibes</p></section><section className="flow-sheet"><div className="sheet-handle"/><h1>Select flavours</h1><p>Choose up to 2 flavours per hookah.</p><label className="flow-search"><Search/><input aria-label="Search flavours" placeholder="Search flavours..." value={flavourSearch} onChange={event=>setFlavourSearch(event.target.value)}/></label><div className="flow-flavour-grid">{visibleFlavours.map(flavour=><FlavourCard key={flavour.id} flavour={flavour} selected={selected.includes(flavour.id)} onToggle={()=>toggleFlavour(flavour.id)}/>)}</div>{visibleFlavours.length===0&&<p className="flavour-empty">No flavours match your search.</p>}<div className="selected-head"><strong>Selected flavours ({selected.length}/{flavourLimit})</strong>{selected.length===flavourLimit&&<span>Maximum selected</span>}</div><div className="flavour-chips">{flavours.filter(item=>selected.includes(item.id)).map(item=><button key={item.id} onClick={()=>toggleFlavour(item.id)}>{item.name}<span>×</span></button>)}</div><PrimaryButton onClick={()=>setStep('delivery')}>Continue</PrimaryButton></section><BottomNav active="flavours"/></main>;
  return <main className="flow-app"><section className="flow-photo-head delivery-head"><img src="/hookah-hero.webp" alt="Hookah hose with drifting smoke"/><Header step={step} cart={cart} onBack={()=>setStep('flavours')}/><p>Your session<br/>your journey</p></section><section className="flow-sheet delivery-sheet"><div className="sheet-handle"/><h1>Delivery and collection</h1><p>Get your session, your way.</p><div className="delivery-options"><DeliveryOption selected={delivery} icon={Truck} title="Delivery" copy="We bring the vibes to you." onClick={()=>setDelivery(true)}/><DeliveryOption selected={!delivery} icon={Store} title="Collection" copy="Pick up and get smoking." onClick={()=>setDelivery(false)}/></div>{delivery&&<label className="booking-row"><MapPin/><span>Delivery address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Enter delivery address"/></span></label>}<label className="booking-row"><Clock3/><span>Select date & time<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></span></label><PrimaryButton onClick={finish}>Continue</PrimaryButton><small className="relax-copy">Relax. We handle the rest.</small></section><BottomNav active="home"/></main>}
