import { ArrowRight, CalendarCheck, MessageCircle, PackageCheck, Truck } from 'lucide-react';
import AppDock from '../components/AppDock';
const steps = [
  { number: '01', icon: PackageCheck, title: 'Build your setup', text: 'Choose your hookah pipes, flavours, coal boxes and optional coal stove.' },
  { number: '02', icon: CalendarCheck, title: 'Share the details', text: 'Tell us your preferred date, location and any useful event notes.' },
  { number: '03', icon: MessageCircle, title: 'Approve & pay', text: 'We confirm availability and delivery pricing, then you pay securely by Yoco or EFT.' },
  { number: '04', icon: Truck, title: 'Enjoy & return', text: 'Receive or collect the setup, enjoy it for 24 hours, then return it for inspection and deposit refund.' },
];
export default function HowItWorks(){return <main><header className="site-header"><a className="brand" href="/"><img src="/chill-pipe-logo.webp" alt="The Chill Pipe" /></a><nav className="main-nav"><a href="/">Book</a><a className="active" href="/how-it-works">How it works</a><a href="/terms">Terms</a></nav><div className="header-note"><span className="pulse" /> 24-hour rentals</div></header><section className="editorial-hero"><p className="eyebrow">Simple from start to smoke</p><h1>Your rental,<br/><em>without the runaround.</em></h1><p>Order, get approved, pay, receive your setup and track the return—all in one clear flow.</p></section><section className="steps-grid">{steps.map(({number,icon:Icon,title,text})=><article className="step-card" key={number}><div className="step-top"><span>{number}</span><Icon size={24}/></div><h2>{title}</h2><p>{text}</p></article>)}</section><section className="closing-panel"><div><p className="eyebrow">Ready when you are</p><h2>Build your setup in a few minutes.</h2></div><a href="/">Start a rental request <ArrowRight size={17}/></a></section><footer><img src="/chill-pipe-logo.webp" alt=""/><p>Bring the chill, we bring the pipe.</p><span>24-hour hookah rentals</span></footer><AppDock active="help"/></main>}
