'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, LockKeyhole, MessageCircle, ShoppingBag } from 'lucide-react';
import AppDock from '../components/AppDock';

type Order = { quantities: Record<string, number>; selectedFlavours: string[]; delivery: boolean; customer: { name: string; phone: string; date: string; location: string; notes: string }; total: number };
const prices: Record<string, number> = { pipe: 550, coal: 50, stove: 150 };
const names: Record<string, string> = { pipe: 'Hookah pipe', coal: 'Coal box (36 pieces)', stove: 'Coal stove' };
const money = (value: number) => `R${value.toLocaleString('en-ZA')}`;

export default function Checkout() {
  const [order, setOrder] = useState<Order | null>(null);
  const [accepted, setAccepted] = useState(false);
  useEffect(() => { const raw = localStorage.getItem('chill-pipe-order'); if (raw) setOrder(JSON.parse(raw)); }, []);
  function updateCustomer(field: keyof Order['customer'], value: string) { setOrder(current => current ? { ...current, customer: { ...current.customer, [field]: value } } : current); }
  function placeOrder() { if (!order) return; const reference = `CP-${Date.now().toString().slice(-6)}`; localStorage.setItem('chill-pipe-booking', JSON.stringify({ ...order, reference, status: 'awaiting_review', deposit: (order.quantities.pipe || 0) * 308, deliveryFee: null })); window.location.href = '/track'; }
  const lines = useMemo(() => order ? Object.entries(order.quantities).filter(([,q]) => q > 0).map(([id,q]) => ({ name:names[id], qty:q, amount:q*prices[id] })) : [], [order]);
  if (!order) return <main className="empty-cart"><ShoppingBag size={34}/><p className="eyebrow">Your cart is empty</p><h1>Build your rental first.</h1><a href="/">Start an order</a></main>;
  const ready = accepted && Boolean(order.customer.name && order.customer.phone && order.customer.date && order.customer.location);
  const request = `Hi The Chill Pipe, I would like to place this rental request.\n\nCustomer: ${order.customer.name}\nWhatsApp: ${order.customer.phone}\nRental date: ${order.customer.date}\nArea: ${order.customer.location}\n\n${lines.map((line)=>`${line.name} x ${line.qty} — ${money(line.amount)}`).join('\n')}\nFlavours: ${order.selectedFlavours.join(', ') || 'None'}\nDelivery & collection: ${order.delivery ? 'Required — quote separately' : 'Not required'}\nOrder estimate: ${money(order.total)}${order.delivery ? ' + delivery/collection' : ''}\nNotes: ${order.customer.notes || 'None'}\n\nI understand that the booking is confirmed once the quoted amount is paid in full.`;
  return <main><header className="site-header"><a className="brand" href="/"><img src="/chill-pipe-logo.png" alt="The Chill Pipe"/></a><div className="checkout-progress"><span className="done"><Check size={12}/> Order</span><i/><span>Checkout</span></div><div className="header-note"><LockKeyhole size={14}/> Secure request</div></header>
    <section className="checkout-head"><a href="/"><ArrowLeft size={15}/> Back to order</a><p className="eyebrow">Final step</p><h1>Review & checkout</h1><p>Check your rental details before placing the request.</p></section>
    <section className="checkout-layout"><div className="checkout-main">
      <section className="checkout-section"><div className="checkout-title"><span>01</span><h2>Contact & event</h2></div><div className="checkout-form"><label><span>Full name</span><input required value={order.customer.name} onChange={e=>updateCustomer('name',e.target.value)} placeholder="Your name"/></label><label><span>WhatsApp number</span><input required type="tel" value={order.customer.phone} onChange={e=>updateCustomer('phone',e.target.value)} placeholder="071 234 5678"/></label><label><span>Rental date</span><input required type="date" value={order.customer.date} onChange={e=>updateCustomer('date',e.target.value)}/></label><label><span>Area / suburb</span><input required value={order.customer.location} onChange={e=>updateCustomer('location',e.target.value)} placeholder="Delivery or collection area"/></label><label className="wide"><span>Booking notes</span><textarea value={order.customer.notes} onChange={e=>updateCustomer('notes',e.target.value)} placeholder="Event time or special request"/></label></div></section>
      <section className="checkout-section"><div className="checkout-title"><span>02</span><h2>Fulfilment</h2></div><div className="fulfilment-card"><div><strong>{order.delivery ? 'Delivery & collection' : 'Customer collection'}</strong><p>{order.delivery ? 'The fee will be confirmed separately based on the location.' : 'Collection and return details will be confirmed with you.'}</p></div><Check size={18}/></div></section>
      <section className="checkout-section"><div className="checkout-title"><span>03</span><h2>Payment</h2></div><div className="payment-card"><div><span>Bank</span><strong>FNB</strong></div><div><span>Account name</span><strong>The Chill Pipe</strong></div><div><span>Account number</span><strong>63108000075</strong></div><div><span>Branch code</span><strong>25065</strong></div></div><p className="payment-note">Payment is only due after availability and the final quotation have been confirmed.</p></section>
    </div><aside className="checkout-aside"><div className="checkout-summary"><p className="eyebrow">Order summary</p>{lines.map((line)=><div className="checkout-line" key={line.name}><span>{line.name} × {line.qty}</span><strong>{money(line.amount)}</strong></div>)}<div className="checkout-line"><span>Flavours × {order.selectedFlavours.length}</span><strong>{money(order.selectedFlavours.length*50)}</strong></div><div className="checkout-line"><span>Refundable deposit</span><strong>{money((order.quantities.pipe||0)*308)}</strong></div><div className="checkout-line muted"><span>Delivery / collection</span><strong>{order.delivery?'TBC':'Not required'}</strong></div><div className="checkout-total"><span>Due after approval</span><strong>{money(order.total+(order.quantities.pipe||0)*308)}</strong></div><label className="accept-row"><input type="checkbox" checked={accepted} onChange={(e)=>setAccepted(e.target.checked)}/><span className="accept-box"><Check size={12}/></span><span>I accept the rental <a href="/terms">terms and conditions</a>.</span></label><button className={ready?'place-order':'place-order disabled'} disabled={!ready} onClick={placeOrder}><MessageCircle size={17}/> Submit for approval</button><p className="fine-print">Availability and delivery pricing are confirmed before payment.</p></div></aside></section><AppDock active="home"/>
  </main>;
}
