'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, LockKeyhole, MessageCircle, ShoppingBag } from 'lucide-react';

type Order = { quantities: Record<string, number>; selectedFlavours: string[]; delivery: boolean; customer: { name: string; phone: string; date: string; location: string; notes: string }; total: number };
const prices: Record<string, number> = { pipe: 450, coal: 50, stove: 150 };
const names: Record<string, string> = { pipe: 'Hookah pipe', coal: 'Coal box (36 pieces)', stove: 'Coal stove' };
const money = (value: number) => `R${value.toLocaleString('en-ZA')}`;

export default function Checkout() {
  const [order, setOrder] = useState<Order | null>(null);
  const [accepted, setAccepted] = useState(false);
  useEffect(() => { const raw = localStorage.getItem('chill-pipe-order'); if (raw) setOrder(JSON.parse(raw)); }, []);
  const lines = useMemo(() => order ? Object.entries(order.quantities).filter(([,q]) => q > 0).map(([id,q]) => ({ name:names[id], qty:q, amount:q*prices[id] })) : [], [order]);
  if (!order) return <main className="empty-cart"><ShoppingBag size={34}/><p className="eyebrow">Your cart is empty</p><h1>Build your rental first.</h1><a href="/">Start an order</a></main>;
  const request = `Hi The Chill Pipe, I would like to place this rental request.\n\nCustomer: ${order.customer.name}\nWhatsApp: ${order.customer.phone}\nRental date: ${order.customer.date}\nArea: ${order.customer.location}\n\n${lines.map((line)=>`${line.name} x ${line.qty} — ${money(line.amount)}`).join('\n')}\nFlavours: ${order.selectedFlavours.join(', ') || 'None'}\nDelivery & collection: ${order.delivery ? 'Required — quote separately' : 'Not required'}\nOrder estimate: ${money(order.total)}${order.delivery ? ' + delivery/collection' : ''}\nNotes: ${order.customer.notes || 'None'}\n\nI understand that the booking is confirmed once the quoted amount is paid in full.`;
  return <main><header className="site-header"><a className="brand" href="/"><img src="/chill-pipe-logo.png" alt="The Chill Pipe"/></a><div className="checkout-progress"><span className="done"><Check size={12}/> Order</span><i/><span>Checkout</span></div><div className="header-note"><LockKeyhole size={14}/> Secure request</div></header>
    <section className="checkout-head"><a href="/"><ArrowLeft size={15}/> Back to order</a><p className="eyebrow">Final step</p><h1>Review & checkout</h1><p>Check your rental details before placing the request.</p></section>
    <section className="checkout-layout"><div className="checkout-main">
      <section className="checkout-section"><div className="checkout-title"><span>01</span><h2>Contact & event</h2></div><div className="detail-grid"><div><span>Name</span><strong>{order.customer.name}</strong></div><div><span>WhatsApp</span><strong>{order.customer.phone}</strong></div><div><span>Rental date</span><strong>{order.customer.date}</strong></div><div><span>Area</span><strong>{order.customer.location}</strong></div></div>{order.customer.notes&&<p className="checkout-notes"><span>Booking notes</span>{order.customer.notes}</p>}</section>
      <section className="checkout-section"><div className="checkout-title"><span>02</span><h2>Fulfilment</h2></div><div className="fulfilment-card"><div><strong>{order.delivery ? 'Delivery & collection' : 'Customer collection'}</strong><p>{order.delivery ? 'The fee will be confirmed separately based on the location.' : 'Collection and return details will be confirmed with you.'}</p></div><Check size={18}/></div></section>
      <section className="checkout-section"><div className="checkout-title"><span>03</span><h2>Payment</h2></div><div className="payment-card"><div><span>Bank</span><strong>FNB</strong></div><div><span>Account name</span><strong>The Chill Pipe</strong></div><div><span>Account number</span><strong>63108000075</strong></div><div><span>Branch code</span><strong>25065</strong></div></div><p className="payment-note">Payment is only due after availability and the final quotation have been confirmed.</p></section>
    </div><aside className="checkout-aside"><div className="checkout-summary"><p className="eyebrow">Order summary</p>{lines.map((line)=><div className="checkout-line" key={line.name}><span>{line.name} × {line.qty}</span><strong>{money(line.amount)}</strong></div>)}<div className="checkout-line"><span>Flavours × {order.selectedFlavours.length}</span><strong>{money(order.selectedFlavours.length*50)}</strong></div><div className="checkout-line muted"><span>Delivery / collection</span><strong>{order.delivery?'TBC':'Not required'}</strong></div><div className="checkout-total"><span>Estimated total</span><strong>{money(order.total)}</strong></div><label className="accept-row"><input type="checkbox" checked={accepted} onChange={(e)=>setAccepted(e.target.checked)}/><span className="accept-box"><Check size={12}/></span><span>I accept the rental <a href="/terms">terms and conditions</a>.</span></label><a className={accepted?'place-order':'place-order disabled'} aria-disabled={!accepted} href={accepted?`https://wa.me/?text=${encodeURIComponent(request)}`:undefined} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Place order request</a><p className="fine-print">This sends your order to WhatsApp for final confirmation.</p></div></aside></section>
  </main>;
}
