'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, Home, LockKeyhole, Menu, MessageCircle, ShoppingBag, Truck } from 'lucide-react';

type Order = { quantities: Record<string, number>; selectedFlavours: string[]; delivery: boolean; customer: { name: string; phone: string; date: string; location: string; notes: string }; total: number };
const prices: Record<string, number> = { pipe: 550, coal: 50, stove: 150 };
const names: Record<string, string> = { pipe: 'Hookah pipe', coal: 'Coal box (36 pieces)', stove: 'Coal stove' };
const money = (value: number) => `R${value.toLocaleString('en-ZA')}`;

export default function Checkout() {
  const [order, setOrder] = useState<Order | null>(null);
  const [accepted, setAccepted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  useEffect(() => { const raw = localStorage.getItem('chill-pipe-order'); if (raw) setOrder(JSON.parse(raw)); }, []);
  function updateCustomer(field: keyof Order['customer'], value: string) { setOrder(current => current ? { ...current, customer: { ...current.customer, [field]: value } } : current); }
  async function placeOrder() { if (!order||submitting) return; setSubmitting(true);try{const response=await fetch('/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(order)});const booking=await response.json();if(!response.ok)throw new Error(booking.error||'Could not create booking.');localStorage.setItem('chill-pipe-booking-access',JSON.stringify({reference:booking.reference,phone:order.customer.phone}));window.location.href=`/track?reference=${encodeURIComponent(booking.reference)}&phone=${encodeURIComponent(order.customer.phone)}`;}catch(error){alert(error instanceof Error?error.message:'Could not create booking.');setSubmitting(false)} }
  const lines = useMemo(() => order ? Object.entries(order.quantities).filter(([,q]) => q > 0).map(([id,q]) => ({ name:names[id], qty:q, amount:q*prices[id] })) : [], [order]);
  if (!order) return <main className="empty-cart"><ShoppingBag size={34}/><p className="eyebrow">Your cart is empty</p><h1>Build your rental first.</h1><a href="/">Start an order</a></main>;
  const ready = accepted && Boolean(order.customer.name && order.customer.phone && order.customer.date && order.customer.location);
  const request = `Hi The Chill Pipe, I would like to place this rental request.\n\nCustomer: ${order.customer.name}\nWhatsApp: ${order.customer.phone}\nRental date: ${order.customer.date}\nArea: ${order.customer.location}\n\n${lines.map((line)=>`${line.name} x ${line.qty} — ${money(line.amount)}`).join('\n')}\nFlavours: ${order.selectedFlavours.join(', ') || 'None'}\nDelivery & collection: ${order.delivery ? 'Required — quote separately' : 'Not required'}\nOrder estimate: ${money(order.total)}${order.delivery ? ' + delivery/collection' : ''}\nNotes: ${order.customer.notes || 'None'}\n\nI understand that the booking is confirmed once the quoted amount is paid in full.`;
  return <main className="flow-app checkout-flow"><section className="flow-photo-head checkout-photo-head"><img src="/hookah-hero.webp" alt="Premium hookah with drifting smoke"/><header className="flow-header"><a href="/?step=delivery" aria-label="Back to delivery"><ArrowLeft/></a><a className="flow-brand" href="/" aria-label="The Chill Pipe home"><img src="/chill-pipe-logo.webp" alt="The Chill Pipe"/><span>Hookah rentals</span></a><div className="flow-head-actions"><span className="checkout-bag"><ShoppingBag/><i>{(order.quantities.pipe||0)+order.selectedFlavours.length}</i></span><span><Menu/></span></div></header><p>Review<br/>confirm<br/>and chill</p></section>
    <section className="flow-sheet checkout-flow-sheet"><div className="sheet-handle"/><div className="checkout-flow-title"><div><h1>Checkout</h1><p>Review your session and send your request.</p></div><span><LockKeyhole/> Secure</span></div>
      <section className="checkout-flow-summary"><div className="summary-heading"><strong>Your session</strong><a href="/?step=home">Edit order</a></div>{lines.map((line)=><div className="checkout-line" key={line.name}><span>{line.name} × {line.qty}</span><strong>{money(line.amount)}</strong></div>)}<div className="checkout-line"><span>{order.selectedFlavours.length} flavours</span><strong>{money(order.selectedFlavours.length*50)}</strong></div>{order.selectedFlavours.length>0?<p className="checkout-flavour-list">{order.selectedFlavours.join(' · ')}</p>:null}<div className="checkout-line"><span>Refundable deposit</span><strong>{money((order.quantities.pipe||0)*308)}</strong></div><div className="checkout-line"><span>{order.delivery?'Delivery & collection':'Customer collection'}</span><strong>{order.delivery?'TBC':'Included'}</strong></div><div className="checkout-total"><span>Due after approval</span><strong>{money(order.total+(order.quantities.pipe||0)*308)}</strong></div></section>
      <section className="checkout-flow-section"><div className="checkout-flow-label"><span>01</span><div><h2>Your details</h2><p>Where we can confirm your booking.</p></div></div><div className="checkout-form"><label><span>Full name</span><input required value={order.customer.name} onChange={e=>updateCustomer('name',e.target.value)} placeholder="Your name"/></label><label><span>WhatsApp number</span><input required type="tel" value={order.customer.phone} onChange={e=>updateCustomer('phone',e.target.value)} placeholder="071 234 5678"/></label><label><span>Rental date & time</span><input required type="datetime-local" value={order.customer.date} onChange={e=>updateCustomer('date',e.target.value)}/></label><label><span>Area / suburb</span><input required value={order.customer.location} onChange={e=>updateCustomer('location',e.target.value)} placeholder="Delivery or collection area"/></label><label className="wide"><span>Booking notes</span><textarea value={order.customer.notes} onChange={e=>updateCustomer('notes',e.target.value)} placeholder="Event time or special request"/></label></div></section>
      <section className="checkout-flow-section"><div className="checkout-flow-label"><span>02</span><div><h2>Fulfilment</h2><p>Your selected handover method.</p></div></div><div className="checkout-flow-fulfilment"><span>{order.delivery?<Truck/>:<Home/>}</span><div><strong>{order.delivery?'Delivery & collection':'Customer collection'}</strong><p>{order.delivery?'The charge will be confirmed for your location before payment.':'Collection and return details will be confirmed with you.'}</p></div><Check/></div></section>
      <section className="checkout-flow-section"><div className="checkout-flow-label"><span>03</span><div><h2>Payment</h2><p>Only after we approve availability.</p></div></div><div className="checkout-bank"><div><span>Bank</span><strong>FNB</strong></div><div><span>Account name</span><strong>The Chill Pipe</strong></div><div><span>Account number</span><strong>63108000075</strong></div><div><span>Branch code</span><strong>25065</strong></div></div></section>
      <label className="checkout-flow-accept"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span className="accept-box"><Check size={12}/></span><span>I accept the rental <a href="/terms">terms and conditions</a>.</span></label><button className={ready?'checkout-flow-submit':'checkout-flow-submit disabled'} disabled={!ready||submitting} onClick={placeOrder}><MessageCircle/>{submitting?'Submitting request…':'Submit for approval'}</button><p className="checkout-flow-note">Availability and delivery pricing are confirmed before payment.</p>
    </section><nav className="flow-nav checkout-flow-nav"><a href="/"><Home/><span>Home</span></a><a href="/?step=flavours"><span className="leaf">◒</span><span>Flavours</span></a><a href="/?step=delivery"><Truck/><span>Delivery</span></a><a className="active" href="/checkout"><ShoppingBag/><span>Checkout</span></a></nav>
  </main>;
}
