'use client';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { clearCustomerDevice } from '@/lib/customer-profile';
export default function ResetForm(){
  const [token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
  const [busy,setBusy]=useState(false),[ready,setReady]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const loaded=useRef(false),lock=useRef(false);
  useEffect(()=>{if(loaded.current)return;loaded.current=true;const f=new URLSearchParams(location.hash.slice(1));if(f.get('type')==='recovery' && f.get('access_token'))setToken(f.get('access_token')!);else if(location.hash)setError('This link is invalid or expired. Request another link.');history.replaceState(null,'',location.pathname);setReady(true);},[]);
  async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;setError('');setMessage('');if(token&&password!==confirm){setError('The passwords do not match.');return;}lock.current=true;setBusy(true);
    try{const r=await fetch('/api/customer/auth/'+(token?'reset':'recover'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(token?{accessToken:token,password}:{email})});const data=await r.json() as {error?:string;message?:string};if(!r.ok)throw new Error(data.error || 'Please retry.');if(token){setToken('');setDone(true);clearCustomerDevice();setMessage('Password saved. Sign in with your new password.');}else setMessage(data.message || 'Check your email.');}
    catch(e){setError(e instanceof Error?e.message:'Could not connect.');}finally{setPassword('');setConfirm('');setBusy(false);lock.current=false;}}
  if(!ready)return <p role="status">Preparing password reset…</p>;
  return <>{!done&&<form onSubmit={submit}>{token?<><label htmlFor="new-password">New password</label><input id="new-password" type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/><label htmlFor="confirm-password">Confirm password</label><input id="confirm-password" type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={busy}/></>:<><label htmlFor="reset-email">Email address</label><input id="reset-email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></>}<button className="cp-login-submit" disabled={busy}>{busy?'Please wait…':token?'Save password':'Send reset link'}</button></form>}{error&&<p className="cp-login-error" role="alert">{error}</p>}{message&&<p className="cp-login-note" role="status">{message}</p>}<a className="cp-login-back" href="/customer-login">Back to sign in</a></>;
}
